services:
  solucao-url-shortener:
    image: ghcr.io/letabilis/desafio-url-shortener:latest
    environment:
      REDIS_ADDR: $REDIS_ADDR
      REDIS_PASSWORD: $REDIS_PASSWORD
    depends_on:
      - redis
    ports:
      - 8080:8080
  redis:
    image: redis:latest
    ports:
      - 6379:6379
