// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/backend-br/desafios/blob/master/url-shortener/PROBLEM.md",
        "contact": {
            "name": "Sahil V. Dowlani",
            "url": "http://github.com/letabilis/desafio-url-shortener",
            "email": "sahilvdowlani@outlook.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/shorten-url": {
            "post": {
                "description": "Responds with a Slug (shortCode) and an Expiry Date (1 day by default)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "url"
                ],
                "summary": "Shorten a Long URL",
                "parameters": [
                    {
                        "description": "The URL to shorten",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.AnyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.ShortenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{slug}": {
            "get": {
                "description": "Fetches the RedisDB and redirects client to original URL",
                "tags": [
                    "url"
                ],
                "summary": "Resolves a short URL to its corresponding long URL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Short URL Slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to the long URL"
                    },
                    "404": {
                        "description": "Short URL not found."
                    }
                }
            }
        }
    },
    "definitions": {
        "types.AnyRequest": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string",
                    "example": "https://example.com"
                }
            }
        },
        "types.ShortenResponse": {
            "type": "object",
            "properties": {
                "expiry": {
                    "type": "string",
                    "example": "2025-08-12T12:19:22.040906963-04:00"
                },
                "slug": {
                    "type": "string",
                    "example": "P3Iww4CcYhA"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "letabilis.github.io",
	BasePath:         "/url-shortener",
	Schemes:          []string{},
	Title:            "URL Shortener API",
	Description:      "This is my solution to the backend-br url-shortener challenge.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
