basePath: /url-shortener
host: letabilis.github.io
info:
  contact:
    email: sahilvdowlani@outlook.com
    name: Sahil V. Dowlani
    url: http://github.com/letabilis/desafio-url-shortener
  description: This is my solution to the backend-br url-shortener challenge.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://github.com/backend-br/desafios/blob/master/url-shortener/PROBLEM.md
  title: URL Shortener API
  version: "1.0"
paths: {}
swagger: "2.0"
