name: Generate swagger docs

on:
  push:
    branches:
      - main

jobs:
  gen-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Install Swag CLI and generate swagger docs
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          swag init -d ./cmd --parseInternal

